
services:
  api:
    build: .
    container_name: mlops_api
    command: uvicorn src.model_deploy:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  monitoring:
    build: .
    container_name: mlops_monitoring
    command: streamlit run src/app.py --server.address 0.0.0.0 --server.port 8501
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    depends_on:
      - api